CREATE TABLE analysis.dm_rfm_segments (
    user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recency int4 NOT NULL,
    frequency int4 NOT NULL,
    monetary_value int4 NOT NULL
);

ALTER TABLE dm_rfm_segments
ADD CONSTRAINT dm_rfm_segments_recency_check CHECK (((recency >= 1) AND (recency <= 5))),
ADD CONSTRAINT dm_rfm_segments_frequency_check CHECK (((frequency >= 1) AND (frequency <= 5))),
ADD CONSTRAINT dm_rfm_segments_monetary_value_check CHECK (((monetary_value >= 1) AND (monetary_value <= 5)))