CREATE TABLE analysis.dm_rfm_segments (
    user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recency int4 NOT NULL,
    frequency int4 NOT NULL,
    monetary_value int4 NOT NULL
)